### ISSUE TITLE
Uncaught Error: Cannot find module 'tree-kill'

### ISSUE THREAD

**Issue by ron-wolf** [atom-haskell/ide-haskell-hoogle#1]
**Atom Version**: 1.13.0-beta8
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.2
**Thrown From**: [ide-haskell-hoogle](https://github.com/atom-haskell/ide-haskell-hoogle) package, v0.0.2

### Stack Trace

Uncaught Error: Cannot find module 'tree-kill'

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:1030

Error: Cannot find module 'tree-kill'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/Ronathan/.atom/packages/ide-haskell-hoogle/lib/hoogle.coffee:4:9)
    at Object.<anonymous> (/Users/Ronathan/.atom/packages/ide-haskell-hoogle/lib/hoogle.coffee:1:1)
    at Module._compile (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.reallyActivate (/Users/Ronathan/.atom/packages/ide-haskell-hoogle/lib/ide-haskell-hoogle.coffee:32:14)
    at /Users/Ronathan/.atom/packages/ide-haskell-hoogle/lib/ide-haskell-hoogle.coffee:21:8
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.triggerActivationHook (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:594:43)
    at Workspace.module.exports.Workspace.handleGrammarUsed (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:618:34)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextEditor.module.exports.TextEditor.handleGrammarChange (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:3282:27)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/tokenized-buffer.js:121:27)
    at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:2858:35)
    at TextEditorRegistry.selectGrammarForEditor (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-registry.js:353:16)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor-registry.js:251:16
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:501:32
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at TextBuffer.module.exports.TextBuffer.setPath (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:379:27)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1125:12)
    at TextEditor.module.exports.TextEditor.saveAs (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:908:26)
    at Pane.module.exports.Pane.saveItemAs (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:766:16)
    at Pane.saveItemAs (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:750:21)
    at Pane.saveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:3:59)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:721:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/workspace.js:693:35)
    at atom-workspace.core:save (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/register-default-commands.js:225:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:41 snippets:previous-tab-stop (input.hidden-input)
     -1:41 editor:outdent-selected-rows (input.hidden-input)
     -1:40.5.0 snippets:previous-tab-stop (input.hidden-input)
     -1:40.5.0 editor:outdent-selected-rows (input.hidden-input)
  2x -1:17.2.0 pane:show-previous-item (input.hidden-input)
  2x -1:11.8.0 pane:show-next-item (input.hidden-input)
     -1:00.8.0 core:cut (input.hidden-input)
  2x -0:59.9.0 core:backspace (input.hidden-input)
     -0:58 markdown-writer:insert-new-line (input.hidden-input)
     -0:58 editor:newline (input.hidden-input)
     -0:57.6.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:57.6.0 editor:newline (input.hidden-input)
     -0:56.8.0 core:paste (input.hidden-input)
  3x -0:53.6.0 core:copy (input.hidden-input)
     -0:11.8.0 application:new-file (input.hidden-input)
     -0:09.7.0 core:save (input.hidden-input)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-clock, v0.1.0 (active)
atom-cursor-indent, v0.1.1 (active)
autocomplete-haskell, v0.6.7 (active)
cursor-history, v0.9.1 (active)
emacs-core-keys, v0.2.3 (active)
fold-comments, v0.6.0 (inactive)
haskell-ghc-mod, v1.19.2 (active)
haskell-pointfree, v0.1.3 (active)
hover-tooltips-hdevtools, v0.10.0 (active)
ide-haskell, v1.8.2 (active)
ide-haskell-cabal, v1.7.1 (active)
ide-haskell-hasktags, v0.0.7 (active)
ide-haskell-hoogle, v0.0.2 (active)
ide-haskell-repl, v0.4.6 (inactive)
language-haskell, v1.10.1 (active)
linter, v1.11.21 (active)
linter-hdevtools, v1.10.0 (active)
linter-hlint, v0.5.0 (active)
markdown-writer, v2.6.2 (active)
minimap, v4.26.5 (active)
minimap-cursorline, v0.2.0 (active)
multi-cursor, v2.1.5 (inactive)
path-copy, v0.14.0 (active)
script, v3.13.0 (inactive)
swap-panes, v0.2.0 (active)
tree-view-open-files, v0.3.0 (active)
vim-mode-plus, v0.75.0 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (active)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (inactive)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.1 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.39.0 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Sorry for the inconvenience and thanks for reporting. Should be fixed in v0.0.3.
